# Generated by Django 5.2.14 on 2026-05-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sphereconversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SphereConversation',
        ),
    ]
