# Generated by Django 5.2.14 on 2026-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_civil_status_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsecurityquestion',
            name='question',
            field=models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What elementary school did you attend?'), ('mother', "What is your mother's maiden name?"), ('city', 'In what city were you born?'), ('friend', 'What is the name of your childhood best friend?'), ('car', 'What was the make of your first car?'), ('street', 'What street did you grow up on?'), ('teacher', "What was your favorite teacher's name?")], default='pet', max_length=255),
        ),
    ]
